# not using sudo
sudo: false

language: cpp

compiler:
  - gcc

before_script:
  - cmake --version
  - python --version

script: 
  - cd ..
  # compile against Orthanc v1.0.0
  - mkdir build100
  - cd build100
  - cmake -DORTHANC_VERSION=1.0.0 ../dwv-orthanc-plugin
  - make
  - cd ..
  # compile against Orthanc v1.1.0
  - mkdir build110
  - cd build110
  - cmake -DORTHANC_VERSION=1.1.0 ../dwv-orthanc-plugin
  - make
  - cd ..
  # compile against Orthanc v1.2.0
  - mkdir build120
  - cd build120
  - cmake -DORTHANC_VERSION=1.2.0 ../dwv-orthanc-plugin
  - make
  - cd ..
  # compile against Orthanc v1.3.0
  - mkdir build130
  - cd build130
  - cmake -DORTHANC_VERSION=1.3.0 ../dwv-orthanc-plugin
  - make
  - cd ..
  # compile against Orthanc v1.4.0
  - mkdir build140
  - cd build140
  - cmake -DORTHANC_VERSION=1.4.0 ../dwv-orthanc-plugin
  - make
  - cd ..
  # compile against Orthanc v1.5.0
  - mkdir build150
  - cd build150
  - cmake -DORTHANC_VERSION=1.5.0 ../dwv-orthanc-plugin
  - make
  - cd ..
